//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExChServer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.ChatMessage = new HashSet<ChatMessage>();
            this.Empl_Chatr = new HashSet<Empl_Chatr>();
        }
    
        public int ID_Employee { get; set; }
        public string Name { get; set; }
        public Nullable<int> ID_Department { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<ChatMessage> ChatMessage { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Empl_Chatr> Empl_Chatr { get; set; }
    }
}
