//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExChServer.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBChatServerEntities : DbContext
    {
        public DBChatServerEntities()
            : base("name=DBChatServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChatMessage> ChatMessage { get; set; }
        public DbSet<Chatroom> Chatroom { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<Empl_Chatr> Empl_Chatr { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
